INSERT INTO Nationality (id, country) VALUES("2", "Albania"); 
INSERT INTO Nationality (id, country) VALUES("3", "Algeria"); 
INSERT INTO Nationality (id, country) VALUES("4", "Andorra"); 
INSERT INTO Nationality (id, country) VALUES("5", "Angola"); 
INSERT INTO Nationality (id, country) VALUES("6", "Antigua and Barbuda"); 
INSERT INTO Nationality (id, country) VALUES("7", "Argentina"); 
INSERT INTO Nationality (id, country) VALUES("8", "Armenia"); 
INSERT INTO Nationality (id, country) VALUES("9", "Australia"); 
INSERT INTO Nationality (id, country) VALUES("10", "Austria"); 
INSERT INTO Nationality (id, country) VALUES("11", "Azerbaijan"); 
INSERT INTO Nationality (id, country) VALUES("12", "Bahamas"); 
INSERT INTO Nationality (id, country) VALUES("13", "Bahrain"); 
INSERT INTO Nationality (id, country) VALUES("14", "Bangladesh"); 
INSERT INTO Nationality (id, country) VALUES("15", "Barbados"); 
INSERT INTO Nationality (id, country) VALUES("16", "Belarus"); 
INSERT INTO Nationality (id, country) VALUES("17", "Belgium"); 
INSERT INTO Nationality (id, country) VALUES("18", "Belize"); 
INSERT INTO Nationality (id, country) VALUES("19", "Benin"); 
INSERT INTO Nationality (id, country) VALUES("20", "Bhutan"); 
INSERT INTO Nationality (id, country) VALUES("21", "Bolivia"); 
INSERT INTO Nationality (id, country) VALUES("22", "Bosnia and Herzegovina"); 
INSERT INTO Nationality (id, country) VALUES("23", "Botswana"); 
INSERT INTO Nationality (id, country) VALUES("24", "Brazil"); 
INSERT INTO Nationality (id, country) VALUES("25", "Brunei"); 
INSERT INTO Nationality (id, country) VALUES("26", "Bulgaria"); 
INSERT INTO Nationality (id, country) VALUES("27", "Burkina Faso"); 
INSERT INTO Nationality (id, country) VALUES("28", "Burundi"); 
INSERT INTO Nationality (id, country) VALUES("29", "Côte d'Ivoire"); 
INSERT INTO Nationality (id, country) VALUES("30", "Cabo Verde"); 
INSERT INTO Nationality (id, country) VALUES("31", "Cambodia"); 
INSERT INTO Nationality (id, country) VALUES("32", "Cameroon"); 
INSERT INTO Nationality (id, country) VALUES("33", "Canada"); 
INSERT INTO Nationality (id, country) VALUES("34", "Central African Republic"); 
INSERT INTO Nationality (id, country) VALUES("35", "Chad"); 
INSERT INTO Nationality (id, country) VALUES("36", "Chile"); 
INSERT INTO Nationality (id, country) VALUES("37", "China"); 
INSERT INTO Nationality (id, country) VALUES("38", "Colombia"); 
INSERT INTO Nationality (id, country) VALUES("39", "Comoros"); 
INSERT INTO Nationality (id, country) VALUES("40", "Congo (Congo-Brazzaville)"); 
INSERT INTO Nationality (id, country) VALUES("41", "Costa Rica"); 
INSERT INTO Nationality (id, country) VALUES("42", "Croatia"); 
INSERT INTO Nationality (id, country) VALUES("43", "Cuba"); 
INSERT INTO Nationality (id, country) VALUES("44", "Cyprus"); 
INSERT INTO Nationality (id, country) VALUES("45", "Czechia (Czech Republic)"); 
INSERT INTO Nationality (id, country) VALUES("46", "Democratic Republic of the Congo"); 
INSERT INTO Nationality (id, country) VALUES("47", "Denmark"); 
INSERT INTO Nationality (id, country) VALUES("48", "Djibouti"); 
INSERT INTO Nationality (id, country) VALUES("49", "Dominica"); 
INSERT INTO Nationality (id, country) VALUES("50", "Dominican Republic"); 
INSERT INTO Nationality (id, country) VALUES("51", "Ecuador"); 
INSERT INTO Nationality (id, country) VALUES("52", "Egypt"); 
INSERT INTO Nationality (id, country) VALUES("53", "El Salvador"); 
INSERT INTO Nationality (id, country) VALUES("54", "Equatorial Guinea"); 
INSERT INTO Nationality (id, country) VALUES("55", "Eritrea"); 
INSERT INTO Nationality (id, country) VALUES("56", "Estonia"); 
INSERT INTO Nationality (id, country) VALUES("57", 'Eswatini (formerly Swaziland)'); 
INSERT INTO Nationality (id, country) VALUES("58", "Ethiopia"); 
INSERT INTO Nationality (id, country) VALUES("59", "Fiji"); 
INSERT INTO Nationality (id, country) VALUES("60", "Finland"); 
INSERT INTO Nationality (id, country) VALUES("61", "France"); 
INSERT INTO Nationality (id, country) VALUES("62", "Gabon"); 
INSERT INTO Nationality (id, country) VALUES("63", "Gambia"); 
INSERT INTO Nationality (id, country) VALUES("64", "Georgia"); 
INSERT INTO Nationality (id, country) VALUES("65", "Germany"); 
INSERT INTO Nationality (id, country) VALUES("66", "Ghana"); 
INSERT INTO Nationality (id, country) VALUES("67", "Greece"); 
INSERT INTO Nationality (id, country) VALUES("68", "Grenada"); 
INSERT INTO Nationality (id, country) VALUES("69", "Guatemala"); 
INSERT INTO Nationality (id, country) VALUES("70", "Guinea"); 
INSERT INTO Nationality (id, country) VALUES("71", "Guinea-Bissau"); 
INSERT INTO Nationality (id, country) VALUES("72", "Guyana"); 
INSERT INTO Nationality (id, country) VALUES("73", "Haiti"); 
INSERT INTO Nationality (id, country) VALUES("74", "Holy See"); 
INSERT INTO Nationality (id, country) VALUES("75", "Honduras"); 
INSERT INTO Nationality (id, country) VALUES("76", "Hungary"); 
INSERT INTO Nationality (id, country) VALUES("77", "Iceland"); 
INSERT INTO Nationality (id, country) VALUES("78", "India"); 
INSERT INTO Nationality (id, country) VALUES("79", "Indonesia"); 
INSERT INTO Nationality (id, country) VALUES("80", "Iran"); 
INSERT INTO Nationality (id, country) VALUES("81", "Iraq"); 
INSERT INTO Nationality (id, country) VALUES("82", "Ireland"); 
INSERT INTO Nationality (id, country) VALUES("83", "Israel"); 
INSERT INTO Nationality (id, country) VALUES("84", "Italy"); 
INSERT INTO Nationality (id, country) VALUES("85", "Jamaica"); 
INSERT INTO Nationality (id, country) VALUES("86", "Japan"); 
INSERT INTO Nationality (id, country) VALUES("87", "Jordan"); 
INSERT INTO Nationality (id, country) VALUES("88", "Kazakhstan"); 
INSERT INTO Nationality (id, country) VALUES("89", "Kenya"); 
INSERT INTO Nationality (id, country) VALUES("90", "Kiribati"); 
INSERT INTO Nationality (id, country) VALUES("91", "Kuwait"); 
INSERT INTO Nationality (id, country) VALUES("92", "Kyrgyzstan"); 
INSERT INTO Nationality (id, country) VALUES("93", "Laos"); 
INSERT INTO Nationality (id, country) VALUES("94", "Latvia"); 
INSERT INTO Nationality (id, country) VALUES("95", "Lebanon"); 
INSERT INTO Nationality (id, country) VALUES("96", "Lesotho"); 
INSERT INTO Nationality (id, country) VALUES("97", "Liberia"); 
INSERT INTO Nationality (id, country) VALUES("98", "Libya"); 
INSERT INTO Nationality (id, country) VALUES("99", "Liechtenstein"); 
INSERT INTO Nationality (id, country) VALUES("100", "Lithuania"); 
INSERT INTO Nationality (id, country) VALUES("101", "Luxembourg"); 
INSERT INTO Nationality (id, country) VALUES("102", "Madagascar"); 
INSERT INTO Nationality (id, country) VALUES("103", "Malawi"); 
INSERT INTO Nationality (id, country) VALUES("104", "Malaysia"); 
INSERT INTO Nationality (id, country) VALUES("105", "Maldives"); 
INSERT INTO Nationality (id, country) VALUES("106", "Mali"); 
INSERT INTO Nationality (id, country) VALUES("107", "Malta"); 
INSERT INTO Nationality (id, country) VALUES("108", "Marshall Islands"); 
INSERT INTO Nationality (id, country) VALUES("109", "Mauritania"); 
INSERT INTO Nationality (id, country) VALUES("110", "Mauritius"); 
INSERT INTO Nationality (id, country) VALUES("111", "Mexico"); 
INSERT INTO Nationality (id, country) VALUES("112", "Micronesia"); 
INSERT INTO Nationality (id, country) VALUES("113", "Moldova"); 
INSERT INTO Nationality (id, country) VALUES("114", "Monaco"); 
INSERT INTO Nationality (id, country) VALUES("115", "Mongolia"); 
INSERT INTO Nationality (id, country) VALUES("116", "Montenegro"); 
INSERT INTO Nationality (id, country) VALUES("117", "Morocco"); 
INSERT INTO Nationality (id, country) VALUES("118", "Mozambique"); 
INSERT INTO Nationality (id, country) VALUES("119", "Myanmar (formerly Burma)"); 
INSERT INTO Nationality (id, country) VALUES("120", "Namibia"); 
INSERT INTO Nationality (id, country) VALUES("121", "Nauru"); 
INSERT INTO Nationality (id, country) VALUES("122", "Nepal"); 
INSERT INTO Nationality (id, country) VALUES("123", "Netherlands"); 
INSERT INTO Nationality (id, country) VALUES("124", "New Zealand"); 
INSERT INTO Nationality (id, country) VALUES("125", "Nicaragua"); 
INSERT INTO Nationality (id, country) VALUES("126", "Niger"); 
INSERT INTO Nationality (id, country) VALUES("127", "Nigeria"); 
INSERT INTO Nationality (id, country) VALUES("128", "North Korea"); 
INSERT INTO Nationality (id, country) VALUES("129", "North Macedonia"); 
INSERT INTO Nationality (id, country) VALUES("130", "Norway"); 
INSERT INTO Nationality (id, country) VALUES("131", "Oman"); 
INSERT INTO Nationality (id, country) VALUES("132", "Pakistan"); 
INSERT INTO Nationality (id, country) VALUES("133", "Palau"); 
INSERT INTO Nationality (id, country) VALUES("134", "Palestine State"); 
INSERT INTO Nationality (id, country) VALUES("135", "Panama"); 
INSERT INTO Nationality (id, country) VALUES("136", "Papua New Guinea"); 
INSERT INTO Nationality (id, country) VALUES("137", "Paraguay"); 
INSERT INTO Nationality (id, country) VALUES("138", "Peru"); 
INSERT INTO Nationality (id, country) VALUES("139", "Philippines"); 
INSERT INTO Nationality (id, country) VALUES("140", "Poland"); 
INSERT INTO Nationality (id, country) VALUES("141", "Portugal"); 
INSERT INTO Nationality (id, country) VALUES("142", "Qatar"); 
INSERT INTO Nationality (id, country) VALUES("143", "Romania"); 
INSERT INTO Nationality (id, country) VALUES("144", "Russia"); 
INSERT INTO Nationality (id, country) VALUES("145", "Rwanda"); 
INSERT INTO Nationality (id, country) VALUES("146", "Saint Kitts and Nevis"); 
INSERT INTO Nationality (id, country) VALUES("147", "Saint Lucia"); 
INSERT INTO Nationality (id, country) VALUES("148", "Saint Vincent and the Grenadines"); 
INSERT INTO Nationality (id, country) VALUES("149", "Samoa"); 
INSERT INTO Nationality (id, country) VALUES("150", "San Marino"); 
INSERT INTO Nationality (id, country) VALUES("151", "Sao Tome and Principe"); 
INSERT INTO Nationality (id, country) VALUES("152", "Saudi Arabia"); 
INSERT INTO Nationality (id, country) VALUES("153", "Senegal"); 
INSERT INTO Nationality (id, country) VALUES("154", "Serbia"); 
INSERT INTO Nationality (id, country) VALUES("155", "Seychelles"); 
INSERT INTO Nationality (id, country) VALUES("156", "Sierra Leone"); 
INSERT INTO Nationality (id, country) VALUES("157", "Singapore"); 
INSERT INTO Nationality (id, country) VALUES("158", "Slovakia"); 
INSERT INTO Nationality (id, country) VALUES("159", "Slovenia"); 
INSERT INTO Nationality (id, country) VALUES("160", "Solomon Islands"); 
INSERT INTO Nationality (id, country) VALUES("161", "Somalia"); 
INSERT INTO Nationality (id, country) VALUES("162", "South Africa"); 
INSERT INTO Nationality (id, country) VALUES("163", "South Korea"); 
INSERT INTO Nationality (id, country) VALUES("164", "South Sudan"); 
INSERT INTO Nationality (id, country) VALUES("165", "Spain"); 
INSERT INTO Nationality (id, country) VALUES("166", "Sri Lanka"); 
INSERT INTO Nationality (id, country) VALUES("167", "Sudan"); 
INSERT INTO Nationality (id, country) VALUES("168", "Suriname"); 
INSERT INTO Nationality (id, country) VALUES("169", "Sweden"); 
INSERT INTO Nationality (id, country) VALUES("170", "Switzerland"); 
INSERT INTO Nationality (id, country) VALUES("171", "Syria"); 
INSERT INTO Nationality (id, country) VALUES("172", "Tajikistan"); 
INSERT INTO Nationality (id, country) VALUES("173", "Tanzania"); 
INSERT INTO Nationality (id, country) VALUES("174", "Thailand"); 
INSERT INTO Nationality (id, country) VALUES("175", "Timor-Leste"); 
INSERT INTO Nationality (id, country) VALUES("176", "Togo"); 
INSERT INTO Nationality (id, country) VALUES("177", "Tonga"); 
INSERT INTO Nationality (id, country) VALUES("178", "Trinidad and Tobago"); 
INSERT INTO Nationality (id, country) VALUES("179", "Tunisia"); 
INSERT INTO Nationality (id, country) VALUES("180", "Turkey"); 
INSERT INTO Nationality (id, country) VALUES("181", "Turkmenistan"); 
INSERT INTO Nationality (id, country) VALUES("182", "Tuvalu"); 
INSERT INTO Nationality (id, country) VALUES("183", "Uganda"); 
INSERT INTO Nationality (id, country) VALUES("184", "Ukraine"); 
INSERT INTO Nationality (id, country) VALUES("185", "United Arab Emirates"); 
INSERT INTO Nationality (id, country) VALUES("186", "United Kingdom"); 
INSERT INTO Nationality (id, country) VALUES("187", "United States of America"); 
INSERT INTO Nationality (id, country) VALUES("188", "Uruguay"); 
INSERT INTO Nationality (id, country) VALUES("189", "Uzbekistan"); 
INSERT INTO Nationality (id, country) VALUES("190", "Vanuatu"); 
INSERT INTO Nationality (id, country) VALUES("191", "Venezuela"); 
INSERT INTO Nationality (id, country) VALUES("192", "Vietnam"); 
INSERT INTO Nationality (id, country) VALUES("193", "Yemen"); 
INSERT INTO Nationality (id, country) VALUES("194", "Zambia"); 
INSERT INTO Nationality (id, country) VALUES("195", "Zimbabwe");
